version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: 'sudo npm install -g yarn@latest lerna@latest'
      - run: yarn install
      - run: cd packages/patterns && yarn build
      - run: cd ../pattern-info && yarn prepare
      - run: cd ../../ && lerna run build
