Unreleased:
  date:
  Added:
    i18n:
      - "[#90](https://github.com/freesewing/freesewing/issues/90):
        Added missing option translations for Benjamin, Florent, Sandy, Shin, and Theo"
  Changed:
    create-freesewing-pattern:
      - Updated dependencies
  Deprecated:
  Removed:
  Fixed:
    benjamin:
      - Added bandLength option to fit optiongroup (it was missing)
    css-theme:
      - Updated styles for DraftConfigurator component for pattern options 3 levels deep
    components:
      - "[#104](https://github.com/freesewing/freesewing.org/issues/104):
        Changed `onDragEnd` to `onChangeCommitted` in slider element
        (change in material-ui API when slider came out of beta)"
      - Workbench now also lets you preload a `withBreasts` set of measurements
      - DraftConfigurator now properly styles pattern options 3 levels deep
    create-freesewing-pattern:
      - Added missing `file-saver` dependency
  Security:

2.0.1:
  date: 2019-09-01
  Added:
    utils:
      - The `measurementDiffers` method is new.
    models:
      - Expanded the size ranges available.
      - Added the `withBreasts` models which were missing in earlier releases.
  Changed:
    models:
      - The models data is now based on the data from the `neckstimate` method in the utils package.
  Fixed:
    theo:
      - "[#78](https://github.com/freesewing/freesewing/issues/78):
        Removed inherited notches from fly shield and side piece."
    models:
      - "[#86](https://github.com/freesewing/freesewing/issues/86):
        The `seatCircumference` measurement was missing, thus making it unavailable on the website"

