Unreleased:
  date:
  Added:
    aaron:
    benjamin:
    bent:
    brian:
    bruce:
    carlita:
    carlton:
    cathrin:
    components:
    core:
    create-freesewing-pattern:
    css-theme:
    examples:
    florent:
    huey:
    hugo:
    i18n:
    jaeger:
    models:
    mui-theme:
    pattern-info:
    patterns:
    plugin-banner:
    plugin-bundle:
    plugin-bust:
    plugin-buttons:
    plugin-cutonfold:
    plugin-debug:
    plugin-designer:
    plugin-dimension:
    plugin-flip:
    plugin-grainline:
    plugin-i18n:
    plugin-logo:
    plugin-round:
    plugin-scalebox:
    plugin-sprinkle:
    plugin-svgattr:
    plugin-theme:
    plugin-title:
    plugin-validate:
    prettier-config:
    rendertest:
    sandy:
    shin:
    simon:
    sven:
    tamiko:
    theo:
    trayvon:
    tutorial:
    utils:
    wahid:
  Changed:
    aaron:
    benjamin:
    bent:
    brian:
    bruce:
    carlita:
    carlton:
    cathrin:
    components:
    core:
    create-freesewing-pattern:
    css-theme:
    examples:
    florent:
    huey:
    hugo:
    i18n:
    jaeger:
    models:
    mui-theme:
    pattern-info:
    patterns:
    plugin-banner:
    plugin-bundle:
    plugin-bust:
    plugin-buttons:
    plugin-cutonfold:
    plugin-debug:
    plugin-designer:
    plugin-dimension:
    plugin-flip:
    plugin-grainline:
    plugin-i18n:
    plugin-logo:
    plugin-round:
    plugin-scalebox:
    plugin-sprinkle:
    plugin-svgattr:
    plugin-theme:
    plugin-title:
    plugin-validate:
    prettier-config:
    rendertest:
    sandy:
    shin:
    simon:
    sven:
    tamiko:
    theo:
    trayvon:
    tutorial:
    utils:
    wahid:
  Deprecated:
    aaron:
    benjamin:
    bent:
    brian:
    bruce:
    carlita:
    carlton:
    cathrin:
    components:
    core:
    create-freesewing-pattern:
    css-theme:
    examples:
    florent:
    huey:
    hugo:
    i18n:
    jaeger:
    models:
    mui-theme:
    pattern-info:
    patterns:
    plugin-banner:
    plugin-bundle:
    plugin-bust:
    plugin-buttons:
    plugin-cutonfold:
    plugin-debug:
    plugin-designer:
    plugin-dimension:
    plugin-flip:
    plugin-grainline:
    plugin-i18n:
    plugin-logo:
    plugin-round:
    plugin-scalebox:
    plugin-sprinkle:
    plugin-svgattr:
    plugin-theme:
    plugin-title:
    plugin-validate:
    prettier-config:
    rendertest:
    sandy:
    shin:
    simon:
    sven:
    tamiko:
    theo:
    trayvon:
    tutorial:
    utils:
    wahid:
  Removed:
    aaron:
    benjamin:
    bent:
    brian:
    bruce:
    carlita:
    carlton:
    cathrin:
    components:
    core:
    create-freesewing-pattern:
    css-theme:
    examples:
    florent:
    huey:
    hugo:
    i18n:
    jaeger:
    models:
    mui-theme:
    pattern-info:
    patterns:
    plugin-banner:
    plugin-bundle:
    plugin-bust:
    plugin-buttons:
    plugin-cutonfold:
    plugin-debug:
    plugin-designer:
    plugin-dimension:
    plugin-flip:
    plugin-grainline:
    plugin-i18n:
    plugin-logo:
    plugin-round:
    plugin-scalebox:
    plugin-sprinkle:
    plugin-svgattr:
    plugin-theme:
    plugin-title:
    plugin-validate:
    prettier-config:
    rendertest:
    sandy:
    shin:
    simon:
    sven:
    tamiko:
    theo:
    trayvon:
    tutorial:
    utils:
    wahid:
  Fixed:
    aaron:
    benjamin:
    bent:
    brian:
    bruce:
    carlita:
    carlton:
    cathrin:
    components:
    core:
    create-freesewing-pattern:
    css-theme:
    examples:
    florent:
    huey:
    hugo:
    i18n:
    jaeger:
    models:
    mui-theme:
    pattern-info:
    patterns:
    plugin-banner:
    plugin-bundle:
    plugin-bust:
    plugin-buttons:
    plugin-cutonfold:
    plugin-debug:
    plugin-designer:
    plugin-dimension:
    plugin-flip:
    plugin-grainline:
    plugin-i18n:
    plugin-logo:
    plugin-round:
    plugin-scalebox:
    plugin-sprinkle:
    plugin-svgattr:
    plugin-theme:
    plugin-title:
    plugin-validate:
    prettier-config:
    rendertest:
    sandy:
    shin:
    simon:
    sven:
    tamiko:
    theo:
    trayvon:
    tutorial:
    utils:
    wahid:
  Security:

2.0.1:
  date: 2019-09-01
  Added:
    utils:
      - The `measurementDiffers` method is new.
    models:
      - Expanded the size ranges available.
      - Added the `withBreasts` models which were missing in earlier releases.
  Changed:
    models:
      - The models data is now based on the data from the `neckstimate` method in the utils package.
  Fixed:
    theo:
      - "[#78](https://github.com/freesewing/freesewing/issues/78):
        Removed inherited notches from fly shield and side piece."
