_types:
  pattern:
    peer:
      "@freesewing/core": "^{{version}}"
      "@freesewing/plugin-bundle": "^{{version}}"
  plugin:
    peer:
      "@freesewing/core": "^{{version}}"
aaron:
  peer:
    "@freesewing/brian": "^{{version}}"
bent:
  peer:
    "@freesewing/brian": "^{{version}}"
carlita:
  peer:
    "@freesewing/bent": "^{{version}}"
    "@freesewing/carlton": "^{{version}}"
    "@freesewing/plugin-bust": "^{{version}}"
    "@freesewing/plugin-buttons": "^{{version}}"
carlton:
  peer:
    "@freesewing/bent": "^{{version}}"
    "@freesewing/plugin-buttons": "^{{version}}"
components:
  peer:
    "react": "^16.4.1"
    "prop-types": "15.7.2"
core:
  _:
    "bezier-js": "^2.2.13"
    "bin-pack": "1.0.2"
    "hooks": "^0.3.2"
create-freesewing-pattern:
  _:
    "chalk": "^2.4.2"
    "commander": "^2.19.0"
    "conf": "^2.2.0"
    "cp-file": "^6.0.0"
    "execa": "^1.0.0"
    "git-config-path": "^2.0.0"
    "github-username": "^4.1.0"
    "globby": "^9.0.0"
    "handlebars": "^4.1.0"
    "inquirer": "^6.2.2"
    "make-dir": "^2.0.0"
    "ora": "^3.1.0"
    "p-each-series": "^1.0.0"
    "parse-git-config": "^3.0.0"
    "validate-npm-package-name": "^3.0.0"
    "which": "^1.3.1"
mui-theme:
  peer:
    "@material-ui/core": "^3.9.3"
    "react": "^16.3.0"
    "react-dom": "^16.3.0"
patterns:
  _:
    "@freesewing/aaron": "^{{version}}"
    "@freesewing/bent": "^{{version}}"
    "@freesewing/brian": "^{{version}}"
    "@freesewing/bruce": "^{{version}}"
    "@freesewing/carlita": "^{{version}}"
    "@freesewing/carlton": "^{{version}}"
    "@freesewing/cathrin": "^{{version}}"
    "@freesewing/florent": "^{{version}}"
    "@freesewing/huey": "^{{version}}"
    "@freesewing/hugo": "^{{version}}"
    "@freesewing/jaeger": "0.2.1"
    "@freesewing/shin": "^{{version}}"
    "@freesewing/simon": "^{{version}}"
    "@freesewing/sven": "^{{version}}"
    "@freesewing/tamiko": "^{{version}}"
    "@freesewing/trayvon": "^{{version}}"
    "@freesewing/wahid": "^{{version}}"
workbench:
  peer:
    "@freesewing/core": "^{{version}}"
    "@freesewing/i18n": "^{{version}}"
    "@freesewing/plugin-theme": "^{{version}}"
    "react-intl": "^2.8.0"
		"typeface-roboto-condensed": "^0.0.54"
