_types:
  pattern:
    peer:
      "@freesewing/core": "^{{version}}"
      "@freesewing/plugin-bundle": "^{{version}}"
    dev:
      "react": "^16.4.1"
      "react-dom": "^16.4.1"
      "@babel/plugin-proposal-class-properties": "^7.0.0"
      "babel-eslint": "10.0.1"
      "eslint": "^5.16.0"
      "babel-jest": "24.7.1"
      "jest": "24.7.1"
      "@freesewing/components": "^{{version}}"
      "@freesewing/css-theme": "^{{version}}"
      "@freesewing/i18n": "^{{version}}"
      "@freesewing/mui-theme": "^{{version}}"
      "@freesewing/patterns": "^{{version}}"
      "@freesewing/plugin-bust": "^{{version}}"
      "@freesewing/plugin-buttons": "^{{version}}"
      "@freesewing/plugin-flip": "^{{version}}"
      "@freesewing/utils": "^{{version}}"
      "@svgr/rollup": "^2.4.1"
      "cross-env": "^5.1.4"
      "gh-pages": "^1.2.0"
      "react-scripts": "^3.0.0"
      "webpack": "4.29.6"
      "rollup": "^0.64.1"
      "rollup-plugin-babel": "^4.0.1"
      "rollup-plugin-babel-minify": "^7.0.0"
      "rollup-plugin-commonjs": "^9.1.3"
      "rollup-plugin-json": "^3.1.0"
      "rollup-plugin-node-resolve": "^3.3.0"
      "rollup-plugin-peer-deps-external": "^2.2.0"
      "rollup-plugin-postcss": "^1.6.2"
      "rollup-plugin-url": "^1.4.0"
      "@material-ui/core": "3.9.3"
      "@material-ui/icons": "3.0.2"
      "@material-ui/lab": "3.0.0-alpha.30"
      "react-intl": "2.8.0"
      "prop-types": "15.7.2"
  plugin:
    peer:
      "@freesewing/core": "^{{version}}"
aaron:
  peer:
    "@freesewing/brian": "^{{version}}"
bent:
  peer:
    "@freesewing/brian": "^{{version}}"
carlita:
  peer:
    "@freesewing/bent": "^{{version}}"
    "@freesewing/carlton": "^{{version}}"
    "@freesewing/plugin-bust": "^{{version}}"
    "@freesewing/plugin-buttons": "^{{version}}"
carlton:
  peer:
    "@freesewing/bent": "^{{version}}"
    "@freesewing/plugin-buttons": "^{{version}}"
css-theme:
  _:
    "open-color": "1.6.3"
components:
  peer:
    "react": "^16.8"
    "prop-types": "15.7.2"
    "@freesewing/pattern-info": "^{{version}}"
    "@freesewing/mui-theme": "^{{version}}"
    "@freesewing/css-theme": "^{{version}}"
    "@freesewing/plugin-react": "^{{version}}"
    "typeface-roboto-condensed": "latest"
    "@freesewing/i18n": "^{{version}}"
    "@freesewing/utils": "^{{version}}"
    "react-intl": "^2.8.0"
    "@material-ui/core": "^3.9.3"
    "@material-ui/icons": "^3.0.2"
    "@material-ui/lab": "^3.0.0-alpha.30"
    "prismjs": "1.16.0"
core:
  _:
    "bezier-js": "^2.2.13"
    "bin-pack": "1.0.2"
    "hooks": "^0.3.2"
create-freesewing-pattern:
  _:
    "chalk": "^2.4.2"
    "commander": "^2.19.0"
    "conf": "^2.2.0"
    "cp-file": "^6.0.0"
    "execa": "^1.0.0"
    "git-config-path": "^2.0.0"
    "github-username": "^4.1.0"
    "globby": "^9.0.0"
    "handlebars": "^4.1.0"
    "inquirer": "^6.2.2"
    "make-dir": "^2.0.0"
    "ora": "^3.1.0"
    "p-each-series": "^1.0.0"
    "parse-git-config": "^3.0.0"
    "validate-npm-package-name": "^3.0.0"
    "which": "^1.3.1"
    "@freesewing/i18n": "^{{version}}"
    "@freesewing/pattern-info": "^{{version}}"
i18n:
  peer:
    "@freesewing/pattern-info": "^{{version}}"
mui-theme:
  peer:
    "@material-ui/core": "^3.9.3"
    "react": "^16.8"
    "react-dom": "^16.8"
pattern-info:
  peer:
    "@freesewing/core": "^{{version}}"
    "@freesewing/plugin-bundle": "^{{version}}"
patterns:
  _:
    "@freesewing/aaron": "^{{version}}"
    "@freesewing/bent": "^{{version}}"
    "@freesewing/brian": "^{{version}}"
    "@freesewing/bruce": "^{{version}}"
    "@freesewing/carlita": "^{{version}}"
    "@freesewing/carlton": "^{{version}}"
    "@freesewing/cathrin": "^{{version}}"
    "@freesewing/florent": "^{{version}}"
    "@freesewing/huey": "^{{version}}"
    "@freesewing/hugo": "^{{version}}"
    "@freesewing/jaeger": "0.2.1"
    "@freesewing/shin": "^{{version}}"
    "@freesewing/simon": "^{{version}}"
    "@freesewing/sven": "^{{version}}"
    "@freesewing/tamiko": "^{{version}}"
    "@freesewing/trayvon": "^{{version}}"
    "@freesewing/wahid": "^{{version}}"
  peer:
    "@freesewing/core": "^{{version}}"
    "@freesewing/plugin-bundle": "^{{version}}"
simon:
  peer:
    "@freesewing/brian": "^{{version}}"
    "@freesewing/plugin-buttons": "^{{version}}"
    "@freesewing/plugin-flip": "^{{version}}"
wahid:
  peer:
    "@freesewing/brian": "^{{version}}"
    "@freesewing/plugin-buttons": "^{{version}}"
    "@freesewing/plugin-round": "^{{version}}"
