noNamespace:
  - create-freesewing-pattern
noRollup:
  - css-theme
  - create-freesewing-pattern
  - mui-theme
  - plugin-theme
  - workbench
extraPackageJson:
  create-freesewing-pattern:
    "reveal": true,
    "bin":
      "create-freesewing-pattern": "index.js"
    "engines":
      "npm": ">=5"
