noNamespace:
  - create-freesewing-pattern
customRollup:
  - css-theme
  - plugin-theme
  - components
  - core
  - i18n
  - utils
packageJson:
  components:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
    files:
      - "Blockquote/*"
      - "Draft/*"
      - "DraftConfigurator/*"
      - "Emblem/*"
      - "Example/*"
      - "Footer/*"
      - "Icon/*"
      - "Logo/*"
      - "Navbar/*"
      - "Ogol/*"
      - "Robot/*"
      - "SampleConfigurator/*"
      - "Spinner/*"
      - "withGist/*"
      - "withLanguage/*"
      - "withStorage/*"
      - "Workbench/*"
  create-freesewing-pattern:
    bin:
      create-freesewing-pattern: index.js
    main: index.js
    module: '!'
    files:
      - lib
      - template
      - README.md
      - package.json
      - '!lib/*.test.js'
      - '!template/default/node_modules'
  css-theme:
    main: dist/theme.css
    module: '!'
  i18n:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
  utils:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
