noNamespace:
  - create-freesewing-pattern
customRollup:
  - css-theme
  - plugin-theme
  - components
  - core
packageJson:
  create-freesewing-pattern:
    "reveal": true
    "bin":
      "create-freesewing-pattern": "index.js"
  css-theme:
    main: "dist/theme.css"
