_:
  clean: "rimraf ../../dist/{{name}}"
  nodebuild: "BABEL_ENV=production rollup -c -o ../../dist/{{name}}/index.js -f cjs"
  modulebuild: "BABEL_ENV=production rollup -c -o ../../dist/{{name}}/index.mjs -f es"
  build: "npm run clean && npm run nodebuild && npm run modulebuild"
  test: "echo \"{{name}}: No tests configured. Perhaps you'd like to do this?\" && exit 0"
  pubtest: "npm publish --registry http://localhost:6662"
_types:
  patterns:
  plugins:
create-freesewing-pattern:
  mkdist: "mkdir -p ../../dist/create-freesewing-pattern"
  copyfiles: "cp -R index.js package.json README.md lib template ../../dist/create-freesewing-pattern/"
  build: "npm run clean && npm run mkdist && npm run copyfiles"
  test: "ava -v && standard *.js lib/*.js"
css-theme:
  build: "npx node-sass --output-style compressed src/theme.scss ../../dist/css-theme/theme.css"
components:
  test: "echo \"{{name}}: No tests configured. Perhaps you'd like to do this?\" && exit 0"
  build: "./scripts/build.sh"
  storybook: "start-storybook -p 6663"
core:
  test: "BABEL_ENV=production nyc mocha tests/*.test.js"
  report: "BABEL_ENV=production nyc report --reporter=html mocha --compilers js:babel-core/register tests/*.test.js"
  coverage: "BABEL_ENV=production nyc npm test && nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov"
workbench:
  test: "cross-env CI=1 react-scripts test --env=jsdom"
  test:watch: "react-scripts test --env=jsdom"

