_:
  clean: "rimraf dist"
  nodebuild: "BABEL_ENV=production rollup -c -o dist/index.js -f cjs"
  modulebuild: "BABEL_ENV=production rollup -c -o dist/index.mjs -f es"
  build: "npm run clean && npm run nodebuild && npm run modulebuild"
  test: "echo \"{{name}}: No tests configured. Perhaps you'd like to do this?\" && exit 0"
  pubtest: "npm publish --registry http://localhost:6662"
  pubforce: "npm publish"
  symlink: "mkdir -p ./node_modules/@freesewing && cd ./node_modules/@freesewing && ln -s -f ../../../* . && cd -"
_types:
  patterns:
  plugins:
create-freesewing-pattern:
  clean: "!"
  nodebuild: "!"
  modulebuild: "!"
  build: "!"
css-theme:
  build: "npx node-sass --output-style compressed src/theme.scss dist/theme.css"
  watch: "npx node-sass --watch --output-style compressed src/theme.scss dist/theme.css"
components:
  test: "echo \"{{name}}: No tests configured. Perhaps you'd like to do this?\" && exit 0"
  storybook: "start-storybook -p 6663"
core:
  test: "BABEL_ENV=production nyc mocha tests/*.test.js"
  report: "BABEL_ENV=production nyc report --reporter=html mocha --compilers js:babel-core/register tests/*.test.js"
  coverage: "BABEL_ENV=production nyc npm test && nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov"
pattern-info:
  prebuild: "node src/prebuild.js"

