storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '**':
    # This is an ephemeral registry used for testing, so we allow all users
    # (including non-authenticated users) to read and publish all packages
    access: $all
    publish: $all
logs:
  - {type: stdout, format: pretty, level: http}
web:
  enable: true
  title: Freesewing mock registry
  logo: "/-/static/logo.svg"
  gravatar: false
  scope:
publish:
  allow_offline: true
listen:
 - localhost:6662
