name: Unit tests - Holmes

on:
  push:
    paths: &files
      - 'packages/holmes/src/**.js'
      - 'packages/holmes/config/**.js'
      - 'packages/holmes/tests/**.js'
      - 'packages/holmes/rollup.config.js'
  pull_request:
    paths: *files

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      env:
        CI: true
      run: cd packages/holmes
    - name: Build pattern
      run: npm run build --if-present
    - name: Run pattern unit tests
      run: npm testonly

