name: Unit tests - Aaron

on:
  push:
    paths:
      - 'packages/aaron/src/**.js'
      - 'packages/aaron/config/**.js'
      - 'packages/aaron/tests/**.js'
      - 'packages/aaron/rollup.config.js'
  pull_request:
    paths:
      - 'packages/aaron/src/**.js'
      - 'packages/aaron/config/**.js'
      - 'packages/aaron/tests/**.js'
      - 'packages/aaron/rollup.config.js'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Change directory
        run: cd packages/aaron
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
      - name: Build pattern
        run: npm run build --if-present
      - name: Run pattern unit tests
      run: npm testonly

