name: Unit tests - Waralee

on:
  push:
    paths: &files
      - 'packages/waralee/src/**.js'
      - 'packages/waralee/config/**.js'
      - 'packages/waralee/rollup.config.js
  pull_request:
    paths: *files

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js $
      uses: actions/setup-node@v1
      with:
        node-version: $
    - run: npm ci
    - run: npm run build --if-present
    - run: npm testonly
      env:
        CI: true
