name: Unit tests - Sandy

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Change directory
        run: cd packages/sandy && npm install
        env:
          CI: true
      - name: Build pattern
        run: cd packages/sandy && npm run build
      - name: Show package.json
        run: cd packages/sandy && cat package.json
      - name: Run pattern unit tests
        run: cd packages/sandy && npm run testonly
