name: Unit tests - Carlita

env:
  CI: true

on:
  push:
    paths:
    - 'packages/carlita/src/**.js'
    - 'packages/carlita/config/**.js'
    - 'packages/carlita/tests/**.js'
    - 'packages/carlita/rollup.config.js'
  pull_request:
    paths:
    - 'packages/carlita/src/**.js'
    - 'packages/carlita/config/**.js'
    - 'packages/carlita/tests/**.js'
    - 'packages/carlita/rollup.config.js'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: cd packages/carlita
    - name: Build pattern
      run: npm run build --if-present
    - name: Run pattern unit tests
      run: npm testonly

