name: Unit tests - Carlita

on:
  push:
    paths: &files
      - 'packages/carlita/src/**.js'
      - 'packages/carlita/config/**.js'
      - 'packages/carlita/rollup.config.js'
  pull_request:
    paths: *files

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js $
      uses: actions/setup-node@v1
      with:
        node-version: $
    - name: Install dependencies
      env:
        CI: true
      run: cd packages/carlita
    - name: Build pattern
      run: npm run build --if-present
    - name: Run pattern unit tests
      run: npm testonly

