name: Unit tests - Fu

on:
  push:
    paths:
    - 'packages/fu/src/**.js'
    - 'packages/fu/config/**.js'
    - 'packages/fu/tests/**.js'
    - 'packages/fu/rollup.config.js'
  pull_request:
    paths:
    - 'packages/fu/src/**.js'
    - 'packages/fu/config/**.js'
    - 'packages/fu/tests/**.js'
    - 'packages/fu/rollup.config.js'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      env:
        CI: true
      run: cd packages/fu
    - name: Build pattern
      run: npm run build --if-present
    - name: Run pattern unit tests
      run: npm testonly

